pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent{
                docker{
                    image 'snakee/golang-junit:1.21'
                    args '-u 0:0' // to run as root user
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
