name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: bugtracker-backend/go.sum

      - name: Execute Backend Unit tests
        working-directory: ./bugtracker-backend
        run: |
          go test -v ./...
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Run backend unit tests
      #   run: |
      #     pytest tests/backend